---
- name: Basic System Setup
  hosts: localhost
  become: true
  tasks:
    - name: Update all security-related packages
      ansible.builtin.package:
            name: "*"
            status: latest
            security: true

    - name: Create a new user
      ansible.builtin.user:
            name: roger
            state: present
            craete_home: true
